### PR TITLE
Add option to parse string from any base

### PR DESCRIPTION
**Pull request by balping**
Currently, `uint256_t` can only be constructed from hexadecimal string literals. This PR adds an option to construct  `uint256_t` from any base, eg. binary, octal, decimal.

Usage:

```c++
uint256_t pd(10, "31415926");
pd == 0x01df5e76ULL; // true
```

### CODE REVIEW

**Comment by balping** [comment]
Note: build only failed because apt-get install failed in one of the many containers. All others have passed.

**Comment by calccrypto** [comment]
Could I ask for the arguments to be swapped?

**Comment by balping** [comment]
> Could I ask for the arguments to be swapped?

No reason, if you prefer the other way round I can change it.

**Comment by calccrypto** [comment]
Yes please

**Comment by balping** [comment]
> Yes please

Done.

**Pull request merged**
